# Generated by Django 4.1 on 2022-12-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searching", "0002_rename_names_cars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="email",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="cars",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="cars",
            table="cars",
        ),
    ]
