# Generated by Django 4.1 on 2022-12-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searching", "0003_alter_cars_email_alter_cars_id_alter_cars_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="cars",
            new_name="carsdata",
        ),
    ]
