# Generated by Django 4.1 on 2022-11-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('page', models.TextField(max_length=5000)),
                ('image', models.ImageField(default=True, upload_to='images')),
            ],
        ),
    ]
