# Generated by Django 4.1 on 2022-11-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteApp', '0002_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
