# Generated by Django 4.1 on 2022-11-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteApp', '0003_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
