# Generated by Django 4.1 on 2022-12-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteApp', '0007_newstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstats',
            name='iph',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='newstats',
            name='oth',
            field=models.IntegerField(default=True),
        ),
    ]
